// patch_comp_intercept.cjs
// 1. Adds a flag-based intercept at the TOP of generateQuizQuestion so comp mode
//    questions are always served, regardless of how the call was resolved.
// 2. Updates _compQuizRunTextQuiz to use the flag approach + adds replay button.
// 3. Stores _compVideoUrl for replay.
const fs = require('fs');
const path = 'public/js/app.js';
let c = fs.readFileSync(path, 'utf8');

// ── PATCH 1: intercept at top of generateQuizQuestion ─────────────────────
const gqOld = 'async function generateQuizQuestion() {\r\n  const grid = document.getElementById(\'quiz-answers-grid\');\r\n  const questionEl = document.getElementById(\'quiz-display-question\');\r\n  if (!grid || !questionEl) return;';
const gqNew = 'async function generateQuizQuestion() {\r\n  // ── COMPREHENSION ADVENTURE INTERCEPT ────────────────────────────────\r\n  // Flag set by _compQuizRunTextQuiz so comp questions are always served\r\n  // even when called as a bare function (scope-chain lookup).\r\n  if (window._compQuizActive && typeof window._compQuizNextFn === \'function\') {\r\n    console.log(\'[CompAdventure] generateQuizQuestion intercepted \u2192 serving comp Q\');\r\n    return window._compQuizNextFn();\r\n  }\r\n\r\n  const grid = document.getElementById(\'quiz-answers-grid\');\r\n  const questionEl = document.getElementById(\'quiz-display-question\');\r\n  if (!grid || !questionEl) return;';

if (!c.includes(gqOld)) { console.error('PATCH 1: pattern not found'); process.exit(1); }
c = c.replace(gqOld, gqNew);
console.log('PATCH 1 applied: intercept at top of generateQuizQuestion');

// ── PATCH 2: replace the window.generateQuizQuestion override in
//    _compQuizRunTextQuiz with flag-based approach + replay button ──────────
const startMarker = '// ── Text quiz (after video) — uses the real quiz engine for 100% parity ────';
const endMarker   = '// ── Image-quadrant quiz ───────────────────────────────────────────────────';
const s = c.indexOf(startMarker);
const e = c.indexOf(endMarker, s);
if (s === -1 || e === -1) { console.error('PATCH 2: markers not found', s, e); process.exit(1); }
console.log('PATCH 2: replacing text-quiz block at chars', s, '-', e);

const newBlock = [
  '// ── Text quiz (after video) — uses the real quiz engine for 100% parity ────',
  'function _compQuizRunTextQuiz(questions, eduLevel) {',
  '  window._compFromQuizQuestions = questions;',
  '  window._compFromQuizTotal     = questions.length;',
  '  window._compFromQuizIdx       = 1; // 0 served immediately below',
  '',
  '  // Translate a comp question → quiz question shape',
  '  const _mkQ = (cq) => {',
  '    const correctAns = (cq.answers || []).find(a => String(a.id) === String(cq.correctId));',
  '    return {',
  '      question: cq.question,',
  '      answers:  (cq.answers || []).map(a => ({ id: a.id, text: a.text, imageKeyword: \'\' })),',
  '      correctId: cq.correctId,',
  '      correctAnswerIds: [cq.correctId],',
  '      subject: \'Comprehension\',',
  '      // Shown by quiz hint system after 1st wrong answer',
  '      hint: [',
  '        cq.explanation || \'\',',
  '        correctAns ? `The correct answer is "${correctAns.text}"` : \'\'',
  '      ].filter(Boolean).join(\' — \'),',
  '      _isCompQuestion: true,',
  '    };',
  '  };',
  '',
  '  // ── Comp-next-question function (called by the intercept inside generateQuizQuestion) ──',
  '  const _compNextFn = () => {',
  '    const nextIdx = window._compFromQuizIdx;',
  '    console.log(\'[CompAdventure] serving Q\', nextIdx + 1, \'of\', questions.length);',
  '    if (nextIdx >= questions.length) {',
  '      // All questions done — restore quiz engine and trigger win',
  '      window._compQuizActive  = false;',
  '      window._compQuizNextFn  = null;',
  '      window._compQuizRestoreFns = null;',
  '      quizSettings.contentTypes  = _origContentTypes;',
  '      quizSettings.correctTarget = questions.length; // already at this score → showQuizWin fires',
  '      quizSettings.hintThreshold = _origHint;',
  '      showQuizWin();',
  '      return;',
  '    }',
  '    window._compFromQuizIdx++;',
  '    quizWrongAttempts = 0;',
  '    const q = _mkQ(questions[nextIdx]);',
  '    quizCurrentQ = q;',
  '    renderQuizBoard(q);',
  '  };',
  '',
  '  // ── Snapshot quiz settings we\'ll temporarily override ──────────',
  '  const _origContentTypes = quizSettings.contentTypes;',
  '  const _origTarget       = quizSettings.correctTarget;',
  '  const _origHint         = quizSettings.hintThreshold;',
  '',
  '  // Restore function for exit-cleanup',
  '  const _restore = () => {',
  '    window._compQuizActive  = false;',
  '    window._compQuizNextFn  = null;',
  '    quizSettings.contentTypes  = _origContentTypes;',
  '    quizSettings.correctTarget = _origTarget;',
  '    quizSettings.hintThreshold = _origHint;',
  '    window._compQuizRestoreFns = null;',
  '  };',
  '  window._compQuizRestoreFns = _restore;',
  '',
  '  // ── Activate the intercept (must happen BEFORE any quiz code runs) ──',
  '  window._compQuizActive = true;',
  '  window._compQuizNextFn = _compNextFn;',
  '  // Kill any stale AI prefetch promise so it can\'t overwrite comp questions',
  '  if (typeof _introPrefetchPromise !== \'undefined\') _introPrefetchPromise = null;',
  '',
  '  // ── Set up quiz view manually (avoid setQuizMode which opens settings overlay) ──',
  '  mode = \'quiz\';',
  '  document.body.classList.add(\'quiz-active\');',
  '  isEditMode = false;',
  '  viewLanding.classList.add(\'hidden\');',
  '  viewEducation.classList.add(\'hidden\');',
  '  viewEdit.classList.add(\'hidden\');',
  '  viewMathGame.classList.add(\'hidden\');',
  '  viewPeppaGame.classList.add(\'hidden\');',
  '  if (viewQuiz) viewQuiz.classList.remove(\'hidden\');',
  '  categoryTabs.classList.add(\'hidden\');',
  '  btnLogout.classList.add(\'hidden\');',
  '',
  '  // ── Build image-sidebar (EduGaze + user + Settings + Exit + Replay) ──',
  '  document.body.classList.add(\'quiz-img-sidebar\');',
  '  let sidebar = document.getElementById(\'quiz-sidebar-controls\');',
  '  if (!sidebar) {',
  '    sidebar = document.createElement(\'div\');',
  '    sidebar.id = \'quiz-sidebar-controls\';',
  '    document.querySelector(\'header\').appendChild(sidebar);',
  '  }',
  '  const _userEl = document.getElementById(\'display-user\');',
  '  const _userInitial = (_userEl?.textContent?.trim() || \'G\')[0].toUpperCase();',
  '  const _username    = _userEl?.textContent?.trim() || \'Guest\';',
  '  const _videoUrl    = window._compVideoUrl || quizSettings.compUrl || \'\';',
  '  sidebar.innerHTML = `',
  '    <div style="display:flex;flex-direction:column;align-items:center;gap:10px;">',
  '      <span class="quiz-sidebar-logo" id="sb-btn-home" title="Double-click or long-press: back to home">EduGaze</span>',
  '      <div class="quiz-sidebar-user" title="${_username}">${_userInitial}</div>',
  '    </div>',
  '    <div style="display:flex;flex-direction:column;align-items:center;gap:8px;">',
  '      <button class="quiz-sidebar-btn" id="sb-btn-replay" title="Double-click or long-press: Replay Video" style="color:#60a5fa;">',
  '        <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 10l4.553-2.276A1 1 0 0121 8.723v6.554a1 1 0 01-1.447.894L15 14M3 8a2 2 0 012-2h8a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z"/></svg>',
  '      </button>',
  '      <button class="quiz-sidebar-btn" id="sb-btn-settings" title="Double-click or long-press: Settings">',
  '        <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>',
  '      </button>',
  '      <button class="quiz-sidebar-btn" id="sb-btn-exit" title="Double-click or long-press: Exit" style="color:#f87171;">',
  '        <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>',
  '      </button>',
  '    </div>`;',
  '  addDoubleTapOrDblClick(document.getElementById(\'sb-btn-home\'),     () => setMode(\'landing\'));',
  '  addDoubleTapOrDblClick(document.getElementById(\'sb-btn-settings\'), () => window.openQuizSettings && window.openQuizSettings());',
  '  addDoubleTapOrDblClick(document.getElementById(\'sb-btn-exit\'),     () => setMode(\'landing\'));',
  '  addDoubleTapOrDblClick(document.getElementById(\'sb-btn-replay\'), () => {',
  '    if (!_videoUrl) return;',
  '    // Show video overlay over the quiz (pause quiz interaction)',
  '    const ov = document.createElement(\'div\');',
  '    ov.id = \'comp-replay-overlay\';',
  '    ov.style.cssText = \'position:fixed;inset:0;background:#000;z-index:9999;display:flex;flex-direction:column;\';',
  '    const ytId = (() => { try { const u = new URL(_videoUrl); return u.searchParams.get(\'v\') || u.pathname.split(\'/\').pop(); } catch(_){return \'\';} })();',
  '    ov.innerHTML = `',
  '      <iframe src="https://www.youtube.com/embed/${ytId}?autoplay=1&rel=0" style="flex:1;border:none;" allow="autoplay;fullscreen"></iframe>',
  '      <button onclick="document.getElementById(\'comp-replay-overlay\').remove()" style="position:absolute;top:12px;right:16px;background:rgba(0,0,0,.6);color:#fff;border:none;border-radius:8px;padding:8px 16px;font-size:1rem;cursor:pointer;z-index:10000;">✕ Close</button>`;',
  '    document.body.appendChild(ov);',
  '  });',
  '',
  '  // Close settings overlay if open',
  '  document.getElementById(\'quiz-settings-overlay\')?.classList.remove(\'show\');',
  '',
  '  // Apply comp-specific settings AFTER any UI init that might restore them',
  '  quizSettings.contentTypes  = [\'text\'];',
  '  quizSettings.hintThreshold = 1;',
  '  quizSettings.correctTarget = questions.length;',
  '',
  '  // Clear state and invalidate any in-flight renders / prefetch',
  '  quizScore = 0;',
  '  quizWrongAttempts = 0;',
  '  quizRenderGen++;',
  '  quizQuestionQueue = [];',
  '  updateQuizScoreBar();',
  '',
  '  // Render first question directly',
  '  const firstQ = _mkQ(questions[0]);',
  '  quizCurrentQ = firstQ;',
  '  console.log(\'[CompAdventure] Starting with\', questions.length, \'questions. Q1:\', firstQ.question);',
  '  renderQuizBoard(firstQ);',
  '}',
  '',
  ''
].join('\n');

c = c.slice(0, s) + newBlock + c.slice(e);
fs.writeFileSync(path, c);
console.log('All patches applied. New file size:', c.length, 'bytes');
